// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"my-biz-backend/boot"
	"my-biz-backend/example"
	"my-biz-backend/example/category"
	"my-biz-backend/traffic"
)

func InitializeHandlers() *Handlers {
	cfg := boot.LoadConfig()
	p := boot.LoadProduct()
	c := boot.LoadCache(cfg)
	w := boot.LoadWeb(cfg)
	database := boot.LoadDB(cfg)
	iamClient := boot.LoadIAM(cfg)

	svc := example.NewServiceExample(database)
	handler := example.NewHandlerExample(svc)

	catSvc := category.NewServiceCategory(database)
	catHandler := category.NewHandlerCategory(catSvc)

	exampleModule := example.NewExample(handler, catHandler, database)
	trafficModule := traffic.NewTraffic(cfg.Traffic)

	return &Handlers{
		Config:  cfg,
		Web:     w,
		DB:      database,
		Cache:   c,
		Product: p,
		IAM:     iamClient,
		Example: exampleModule,
		Traffic: trafficModule,
	}
}
